### ISSUE TITLE
Réécriture en JavaScript

### ISSUE THREAD

**Issue by Mickael-van-der-Beek** [LuxOrik/Kdiv2#1]
Pour moderniser ce projet je pense qu'une réécriture complète en JavaScript s'impose.

**Comment by LuxOrik** [comment]
Depuis quand les kiwis ont le droit d'utiliser internet ?

**Comment by LuxOrik** [comment]
Fixed #e641805dcb657ffae99e979bd464616ac1ba396f

**Comment by Mickael-van-der-Beek** [comment]
Je vais me plaindre à mon syndicat!
